### ISSUE TITLE
求修复：jenkins调用，“测试计划”下拉列表加载错误

### ISSUE THREAD

**Issue by devoptrina** [metersphere/jenkins-plugin#8]
v1.6.0  jenkins日志
SEVERE	i.m.commons.utils.LogUtil#error: Method[doFillTestPlanIdItems][Request method 'GET' not supported]
io.metersphere.commons.exception.MeterSphereException: Request method 'GET' not supported
	at io.metersphere.client.MeterSphereClient.call(MeterSphereClient.java:155)
	at io.metersphere.client.MeterSphereClient.call(MeterSphereClient.java:139)
	at io.metersphere.client.MeterSphereClient.getTestPlanIds(MeterSphereClient.java:94)
	at io.metersphere.MeterSphereBuilder$DescriptorImpl.doFillTestPlanIdItems(MeterSphereBuilder.java:405)

ps: 1.6.1 也没修复

**Comment by wangzhen-fit2cloud** [comment]
你好，请更新 metersphere 及插件到 1.7.3 版本进行验证。
